bao-project/bao-ci

docker/Dockerfile

To contemplate the new checkers to be used on CI, the Dockerfile had to be modified:
- doc8: style checker for reST documentation
- cspell: spell checker for code (requirements: npm, nodejs)
- sphinxcontrib-spelling: sphinx extension for spell cheking reST documentation (requirements: enchant, pyenchant)
Other non-checker related packages:
- sphinx-tabs: extension to be used on the documentation to enable interactive tabbed content
- sphinx-rtd-theme: sphinx theme
Note: the docker image has already been updated on docker-hub

feat(docker-checkers): add new sphinx checkers to the Dockerfile

---

ci.mk

On partitioner-atf, the ci submodule cannot depend on the ATF definition of CPPFLAGS, since some compiler flags are
passed on this variable. This will make the checkers fail when called.
To solve this, each checker that needs the CPPFLAGS has now an extra parameter to be passed to the function call.
Signed-off-by: Daniel Oliveira <drawnpoetry@gmail.com>

fix(ci-calls): remove checkers calls dependency on CPPFLAGS

---

ci.mk

This is a quick fix to add gitlint rule as a non build target to prevent calling it with the PLATFORM argument.
Signed-off-by: Daniel Oliveira <drawnpoetry@gmail.com>

Fix: Add gitlint rule as a non build target

---

ci.mk

In the development of partitioner-atf, we want to run the CI pipeline on all the code that interfaces partitioner-standalone with ATF. 
To achieved that we needed to include a sub-makefile that calls the ci functions. This sub-makefile is called during the workflow of ATF's building process. To exclude explicit includes of ATF from the misra-checker header files, we added a new parameter to be passed through the `misra-check` function. Such argument will hold a suppression list in the format expected by cppcheck `--suppress=<spec>`, which in the specific case of partitioner-atf is the full content of the `include` folder belonging to ATF.

fix(ci-calls): add a 4th parameter to misra checker call to pass suppressions

---

.github/workflows/base.yml
.github/workflows/docker.yml

This PR instantiates the base workflow which includes the gitlint, license, yamllint and pylint checks o these checks are also ran on PRs in the bao-ci repo itself.
Also it adds a workflow that automates the build and publishing of the docker image to Docker Hub if an accepted PR contains modifications to the Dockerfile. The Docker Hub login secrets (user name and token) were already created for the repository.

Add workflows for the ci repo itself

---

.gitlint

This small PR introduces to the gitlint configuration file a new commit/branch type, namely `update`. Moreover, it also adds the `opt` tag already considered on the documentation.
* update:  changes that brings a feature, setup, or configuration up to date by adding new or updated information (e.g., updating a version, adding a new item to a list, updating CODEOWNERS, bumping the CI repo)
* opt: modifications pertaining only to optimizations 
bao-docs: https://github.com/bao-project/bao-docs/pull/24

feat(gitlint): add update and opt tag to gitlint

---

.github/workflows/docker.yml

The workflow for publishing the docker image was not being triggered because the target branch name for which the workflow was dispatched was named 'master' instead of 'main'
Signed-off-by: Jose Martins <josemartins90@gmail.com>

fix(workflows/docker): fix target branch name

---

.github/workflows/base.yml
.github/workflows/templates/base.yml

Otherwise the check we fail if we are not on a PR, since 'github.event.pull_request.base.sha' is not defined when a workflow is triggered on a push to main or manually via workflow_dispatch.
Signed-off-by: Jose Martins <josemartins90@gmail.com>

fix(workflows/gitlint): use different base commit for different triggers

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/pull_request_template.md
.github/templates/ISSUE_TEMPLATE/bug_report.md
.github/templates/ISSUE_TEMPLATE/feature_request.md
.github/templates/pull_request_template.md

This change adds a PR and issues template for the bao-ci repository. Moreover, a new folder has created in `.github/templates` to aggregate general templates to be used by other @bao-project/maintainers  on their own repos. Please use them on your own repos, after this PR is introduced.
- **feat**: introduces a new functionality
- Logical unit: PR and Issues templates

feat/gh-templates: add templates for PRs/Issues and provision the repo with templates

---

ci.mk

Fix a Makefile rule error in generating the `.cppcheck-types.cfg` file, by correctly invoking the c compiler.
Before this fix, make would not correctly generate `.cppcheck-types.cfg` file, preventing it from running the misra-check rule successfully.
This error affects the misra makefile rules, misra-check in particular.

fix: correctly invoke compiler in misra rule

---

ci.mk

Reverts bao-project/bao-ci#30
The problem was really non-existent. @DavidMCerdeira was including ci.mk in a Makefile where `cc` was not defined. In the future we should clearly document and call attention to what variables must be defined before including ci.mk

Revert "fix: correctly invoke compiler in misra rule"

---

README.md
docker/Makefile

Signed-off-by: Jose Martins <josemartins90@gmail.com>
When using the [docker Makefile](https://github.com/bao-project/bao-ci/blob/ed64185520b6e4e243edbe183cd1de771e3b50c7/docker/Makefile) to run the container, it will build and/or fetch the image using the `latest` tag. The [docker worflow](https://github.com/bao-project/bao-ci/blob/main/.github/workflows/docker.yml) will also publish the updated container image to Docker Hub always using the same tag. So, if in a given commit the [Dockerfile](https://github.com/bao-project/bao-ci/blob/ed64185520b6e4e243edbe183cd1de771e3b50c7/docker/Dockerfile) is updated, a less attentive user that already had a container image locally may not notice the change and keep running the same image they had previously fetched or built.
This PR updates the …

feat(docker): always check latest docker image

---

ci.mk
util.mk

As pointed out in #32, certain variables such as 'cc' must be defined by the Makefile that instantiates certain CI rules. There was no measure put in place to check that these variables were indeed defined. This PR introduces these checks by:
- Creating an utility function that checks if the argument variable is defined;
- Adding the check for the 'root_dir' variable which must be defined before ci.mk is included;
- Adding the check for the 'cc' variable that must be defined when the 'cppcheck' rules are instantiated.

Check for variables that must defined in ci.mk

---

ci.mk

This PR changes the way the clang-format rule locates the configuration file by directly pointing to it instead of relying on its relative position in the project directory structure.
In previous clang versions  '.clang-format' file had to be located " located in one of the parent directories of the source file (or current directory for stdin).", which made us have to copy the file to the root of the project we were analyzing. In clang-format-14 it is possible to directly point to it by defining the option '-style=file:/path/to/.clang-format'.
@DavidMCerdeira  suggested this in #36 
In essence, this PR *fixes* the way the .clang-format file is located.

fix(clang-format): point directly to .clang-format config file

---

ci.mk

Add missing targets to the non_build_targets variable.
- **fix**: bug fix
- Logical unit: ci-mk

fix(ci-rules): add missing non build targets to the make variable

---

license_check.py

Small style changes on the output of the `license_checker.py` script to prevent the output of the absolute path of the file being parsed, which can make it to confusing.
- **style**: changes that do not affect the meaning of the code (formatting, typos, naming, etc.)

style(lic-checker): change print of abs path to only rel path

---

docker/Dockerfile

Add the pyspellchecker python library to dockerfile.
The pyspellchecker python library is used to implement our own spellchecking scripts.

feat: Add spellchecking python library

---

.github/workflows/docker.yml

The current docker build and publish workflow uses baoproj instead of baoproject tag.
This results in an error that prevents the workflow from publishing a newly built docker to dockerhub.
To fix this, the commit updates the appropriate field in .github/workflows/docker.yml

fix: Use correct tag in docker build and publish workflow

---

docker/Dockerfile

Add the ropgadget, capstone and gitpyhton python libraries to dockerfile.
These libraries are used by the `rop_gadget` checker. 
- **feat**: introduces a new functionality
- Logical unit: dockerfile

feat(docker): add ropgadget, capstone, gitpython libraries

---

.github/workflows/templates/c.yaml
Makefile
ci.mk
rops_check.py

This PR introduces a script designed to compare the number of ROP gadgets between two branches of a Git repo. It uses the ROPGadget tool to measure the ROP gadgets in the specified executable files. The primary goal of this checker is to monitor and control the growth of ROP gadgets in a designated repo.
The script takes the following inputs:
- `-s --source-branch`: Source branch name (default: current branch)
- `-t --target-branch`: Target branch name (default: main)
- `-b --build-cmd`: Build command to compile the repository
- `-x --exe-path`: Path to the executable file to be measured
It then calculates the difference in the number of ROP gadgets and the percentage change between the two branches. If the increase in ROP gadgets exceeds the defined percentage threshold (currently set to …

feat(rops-checker): add rops_check script to measure rops 

---

.github/workflows/templates/misc.yaml
ci.mk

This PR comes in segment with the PR https://github.com/bao-project/bao-docs/pull/68. It adds the ``doc8`` style checker to ``ci.mk`` and a github action on templates to run it.
- **feat**: introduces a new functionality
- Logical unit: <ci-mk>

feat/doc8: add checker to ci.mk

---

ci.mk

This modification allows the inclusion of *ci.mk* before the definition of the first Makefile target, which is assumes is `all`, the typical Makefile convention.

feat(ci.mk): allow inclusion before 'all' target

---

util.mk

This PR introduces make utility functions in *util.mk* that list files in a given directory, which are useful for listing the files later passed to the CI make rules. For example:
```make
include $(root_dir)/ci/ci.mk
c_src_files=$(call list_dir_files_recursive, src, *.c)
c_hdr_files=$(call list_dir_files_recursive, src, *.h)
c_files=$(c_src_files) $(c_hdr_files)
$(call ci, format, $(c_files))
```

feat(util): add make functions for listing files

---

docker/Dockerfile

This PR adds the arm aarch32 toolchain needed to compile fvp-r-aarch32 platform in the bao-hypervisor.
I've built the container locally and tested building fvp-r-aarch32 in it and it seems to be working fine.

feat(docker): add arm aarch32 toolchain

---

docker/Dockerfile

This PR refactors the Dockerfile tool installation commands so the final image is divided into multiple layers. This has the main advantage of speeding up docker image builds.

ref(docker): separate tools installation in logical layers

---

.clang-format
ci.mk
docker/Dockerfile

This PR updates clang-tidy and clang-format tools to version 18 and also the .clang-format file with the newly available options for formatting.
This PR depends on #60.

Update clang tools version in docker and .clang-format options

---

.clang-format

Just a couple of adjustments to the clang-format configurations.

update: misc clang-format options

---

README.md

This PR only updates the bao-ci readme with the HIS metrics source code checker.
It does not change any functionality of the repo.

doc(readme): update CI readme to include HIS metrics checker

---

docker/Dockerfile

This PR implements the necessary changes to the Dockerfile, enabling support for both aarch64 and risc-v versions of qemu. The updates encompass the following changes:
1. Updated base dependencies required for building qemu (commit https://github.com/bao-project/bao-ci/pull/73/commits/96be375d352c211e8e9dbb38de8e042df7a3ef73);
2. Addded installation steps for qemu-riscv64 (commit https://github.com/bao-project/bao-ci/pull/73/commits/da9edbe4d02e8685333db92ba6f605989876d8f0);
3. Included installation steps for qemu-aarch64 (commit https://github.com/bao-project/bao-ci/pull/73/commits/deb712e272fa1c875c2bb2631cd18e955dce0995).
Aditionally, commit https://github.com/bao-project/bao-ci/pull/73/commits/7a83e9bf78f1b1f65285c18ea31c2a549f0a3a5c introduces utility commands, including the `tree` …

feat(qemu): add support for qemu-aarch64 and qemu-riscv64 in Docker

---

docker/Dockerfile

clang-format-19 introduces format unwanted format changes with no way to fix them in a scalable manner. We will wait for version 20 to understand if this issue is fixed.

fix(format): revert back clang version to 18

---

docker/Dockerfile

This PR adds as LLVM to the Bao docker in preparation for clang support in Bao.

feat(docker): Add llvm, clang and linker

---

docker/Makefile

Fix an issue where commands such as `make -C ci/docker format` do not execute, by setting a consistent capitalization for ROOT_DIR variable in the docker Makefile.

fix(docker): Fix docker makefile variable
